alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: livewell-ui
    match:
      path:
        prefix: /
name: jellyfish-app
region: lon
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: jones-agyemang/livewell-ui
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: livewell-ui
  run_command: npm start
  source_dir: /
