name: Deploy React App

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the React app
    - name: Build the app
      run: npm run build

    # Step 5: Deploy the app using DigitalOcean
    - name: Deploy the app
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Replace with your secret variable